remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title:  Ryotaro Ohashi
#logo: 
description:  Data Analyst | Consultant | Healthcare
#show_downloads: true
theme:  jekyll-theme-minimal
