
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Ryotaro Ohashi
description: Consultant | Data Analytics | Healthcare

logo: /assets/img/profilepic_circle.png

#show_downloads: true
#theme:  jekyll-theme-minimal
